package main

var hitCheers = []string{
	"Ass duly kicked!",
	"Bring him down!!",
	"Deine Mudder kann nix!",
	"Did you see that?",
	"Don't tell your mama.",
	"Gonna cry.",
	"He did not see that coming",
	"Hit me baby one more time!",
	"I will tell your mama!",
	"Just like in the movies",
	"Kill me now!",
	"Kill me someone!",
	"Like anyone cares...",
	"Like my mama!",
	"Like your mama!",
	"Meine Mudder kann alles!",
	"Oh, dear...",
	"Oh, why him?",
	"On a wing and a prayer now...",
	"Pretty hard!",
	"Really?",
	"Right in his face!",
	"That took very long!",
	"That was quick!",
	"That's in the records!",
	"Unbelievable!",
	"Was that Maverik?",
	"Watch your six, dude.",
	"Where is Goose?",
	"Yes!",
}

var scoreCheers = []string{
	"And slapped his butt!",
	"Applause for this awesome hit!",
	"As hard as he could!",
	"Can he do it again?",
	"Cheers!",
	"Gimme more!",
	"Good one.",
	"He sticks like glue!",
	"Kill, kill, kill!",
	"Nice shot!",
	"Pure luck!",
	"Shoot, baby, shoot!",
	"Well deserved, really.",
	"Wohooo!",
}
