package main

var hitCheers = []string{
	"Nice shot!",
	"He sticks like glue!",
	"Like anyone cares...",
	"Shoot, baby, shoot!",
	"Gimme more!",
	"Pure luck!",
	"Good one.",
	"Watch your six, dude.",
	"Unbelievable!",
	"Yes!",
	"Oh, why him?",
	"Can he do it again?",
	"Oh, dear...",
	"Kill, kill, kill!",
	"Really?",
	"Well deserved, really.",
	"Don't tell your mama.",
	"Did you see that?",
	"On a wing and a prayer now...",
	"He did not see that coming",
	"That was quick!",
	"That took very long!",
	"I will tell your mama!",
	"Like your mama!",
	"Like my mama!",
	"As hard as he could!",
	"Right in his face!",
	"And slapped his butt!",
	"That's in the records!",
	"Pretty hard!",
	"Applause for this awesome hit!",
	"Cheers!",
	"Wohooo!",
	"Gonna cry.",
	"Just like in the movies",
	"Was that Maverik?",
	"Where is Goose?",
	"Deine Mudder kann nix!",
	"Meine Mudder kann alles!",
	"Ass duly kicked!",
	"Kill me someone!",
	"Hit me baby one more time!",
	"Kill me now!",
	"Bring him down!!",
}
